# Generated by Django 4.1.1 on 2022-09-07 16:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('otp_email', models.EmailField(max_length=254)),
                ('time_created', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('college_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a 10 digit phone number.', regex='^[0-9]{10}$')])),
                ('department', models.CharField(choices=[('Applied Sciences & Humanities', 'Applied Sciences & Humanities'), ('Electronics And Communication Engineering', 'Electronics And Communication Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical And Electronics Engineering', 'Electrical And Electronics Engineering'), ('Computer Science And Engineering', 'Computer Science And Engineering'), ('Information Technology', 'Information Technology'), ('Master Of Computer Applications', 'Master Of Computer Applications')], max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('fdp_type', models.CharField(choices=[('Face to Face FDP', 'Face to Face FDP'), ('Online', 'Online')], max_length=50)),
                ('face_to_face_fdp', models.CharField(blank=True, choices=[('AKTU Level-1 (UHV-II)', 'AKTU Level-1 (UHV-II)'), ('AKTU Refresher', 'AKTU Refresher'), ('AKTU Level-2 (UHV-III)', 'AKTU Level-2 (UHV-III)'), ('AKTU Level-3 (UHV-III)', 'AKTU Level-3 (UHV-III)'), ('AKTU 10 days FDP on UHBC (UHV-III)', 'AKTU 10 days FDP on UHBC (UHV-III)'), ('AKTU 10 days FDP on VREHC (UHV-III)', 'AKTU 10 days FDP on VREHC (UHV-III)'), ('AKTU 10 days FDP on HVMD', 'AKTU 10 days FDP on HVMD'), ('AICTE UHV-II', 'AICTE UHV-II'), ('AICTE UHV-III', 'AICTE UHV-III'), ('AICTE UHV-IV', 'AICTE UHV-IV')], max_length=200, null=True)),
                ('online_fdp', models.CharField(blank=True, choices=[('AICTE-Five Days Introductory FDP', 'AICTE-Five Days Introductory FDP'), ('AICTE-UHV Refresher Part-I', 'AICTE-UHV Refresher Part-I'), ('AICTE-UHV Refresher Part-II', 'AICTE-UHV Refresher Part-II'), ('AICTE-5 Day Online UHV-I', 'AICTE-5 Day Online UHV-I'), ('AICTE-6 Day Online UHV-II', 'AICTE-6 Day Online UHV-II'), ('AKTU-HV in Shankya and Vedant Darshan (eight days)', 'AKTU-HV in Shankya and Vedant Darshan (eight days)'), ('AKTU-HV in Jain and Baudh Darshan (eight days)', 'AKTU-HV in Jain and Baudh Darshan (eight days)')], max_length=200, null=True)),
                ('starting_date', models.CharField(max_length=15)),
                ('end_date', models.CharField(max_length=15)),
                ('number_of_days', models.PositiveBigIntegerField()),
                ('venue', models.CharField(max_length=250)),
                ('certificate_number', models.CharField(max_length=250)),
                ('certificate', models.FileField(upload_to='')),
                ('incentive_detail', models.CharField(choices=[('AKTU Level-2 (10,000)', 'AKTU Level-2 (10,000)'), ('AKTU Level-3 (15,000)', 'AKTU Level-3 (15,000)'), ('AICTE UHV-III (10,000)', 'AICTE UHV-III (10,000)'), ('AICTE UHV-IV (15,000)', 'AICTE UHV-IV (15,000)'), ('Not Taken Yet', 'Not Taken Yet')], max_length=50)),
                ('remarks', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
