# Generated by Django 4.1.1 on 2022-10-10 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a 10 digit phone number.', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='face_to_face_fdp',
            field=models.CharField(blank=True, choices=[('AKTU Level-1', 'AKTU Level-1'), ('AKTU Refresher', 'AKTU Refresher'), ('AKTU Level-2', 'AKTU Level-2'), ('AKTU Level-3', 'AKTU Level-3'), ('AKTU 10 days FDP on UHBC', 'AKTU 10 days FDP on UHBC'), ('AKTU 10 days FDP on VREHC', 'AKTU 10 days FDP on VREHC'), ('AKTU 10 days FDP on HVMD', 'AKTU 10 days FDP on HVMD'), ('AICTE UHV-II', 'AICTE UHV-II'), ('AICTE UHV-III', 'AICTE UHV-III'), ('AICTE UHV-IV', 'AICTE UHV-IV')], max_length=200, null=True),
        ),
    ]
