# Generated by Django 4.1.1 on 2022-09-28 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyParticipationForm',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a 10 digit phone number.', regex='^[0-9]{10}$')])),
                ('name_of_event', models.CharField(max_length=255)),
                ('venue_of_activity', models.CharField(max_length=255)),
                ('duration', models.PositiveBigIntegerField()),
                ('starting_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
