# Generated by Django 4.1.1 on 2022-10-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_user_college_email_user_department_user_designation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('user', 'college_email', 'phone_number', 'name', 'department', 'designation', 'fdp_type', 'face_to_face_fdp', 'online_fdp', 'starting_date', 'end_date', 'venue', 'certificate_number', 'incentive_detail'), name='unique appversion'),
        ),
    ]
