# Generated by Django 4.1.1 on 2022-09-16 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_remove_user_college_email_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='college_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a 10 digit phone number.', regex='^[0-9]{10}$')]),
        ),
    ]
