# Generated by Django 4.1.1 on 2022-09-23 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_registration_college_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=25)),
                ('section', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a 10 digit phone number.', regex='^[0-9]{10}$')])),
                ('name_of_activity', models.CharField(max_length=255)),
                ('venue_of_activity', models.CharField(max_length=255)),
                ('number_of_days', models.PositiveBigIntegerField()),
                ('starting_date', models.CharField(max_length=15)),
                ('end_date', models.CharField(max_length=15)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
