# Generated by Django 4.1.1 on 2022-09-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentForm',
        ),
    ]
