# Generated by Django 4.1.1 on 2022-10-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_remove_registration_unique registration_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='unique registration',
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('name', 'department', 'college_email', 'phone_number', 'face_to_face_fdp', 'online_fdp', 'starting_date', 'end_date', 'certificate_number', 'incentive_detail', 'venue'), name='unique registration'),
        ),
    ]
