# Generated by Django 4.1.1 on 2022-10-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_remove_registration_unique registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='course',
            field=models.CharField(default=None, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentform',
            name='roll_no',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='online_fdp',
            field=models.CharField(blank=True, choices=[('AICTE-UHV Refresher Part-I', 'AICTE-UHV Refresher Part-I'), ('AICTE-UHV Refresher Part-II', 'AICTE-UHV Refresher Part-II'), ('AICTE-5 Day Online UHV-I', 'AICTE-5 Day Online UHV-I'), ('AICTE-6 Day Online UHV-II', 'AICTE-6 Day Online UHV-II'), ('AKTU-HV in Shankya and Vedant Darshan (eight days)', 'AKTU-HV in Shankya and Vedant Darshan (eight days)'), ('AKTU-HV in Jain and Baudh Darshan (eight days)', 'AKTU-HV in Jain and Baudh Darshan (eight days)')], max_length=200, null=True),
        ),
    ]
