# Generated by Django 4.1.1 on 2022-10-11 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_studentform_course_studentform_roll_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='number_of_days',
        ),
    ]
