# Generated by Django 4.1.1 on 2022-10-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_remove_studentform_number_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='number_of_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
