# Generated by Django 4.1.1 on 2022-10-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_studentform_number_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='starting_date',
            field=models.DateField(),
        ),
    ]
