# Generated by Django 4.1.1 on 2022-10-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_alter_registration_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyparticipationform',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
