# Generated by Django 4.1.1 on 2022-10-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0019_alter_facultyparticipationform_remarks_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentform',
            constraint=models.UniqueConstraint(fields=('name', 'email', 'roll_no', 'starting_date', 'end_date', 'venue_of_activity', 'name_of_activity'), name='unique student registration'),
        ),
    ]
