# Generated by Django 4.1.1 on 2022-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_studentform_unique student registration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='unique registration',
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('name', 'department', 'college_email', 'phone_number', 'starting_date', 'end_date'), name='unique registration'),
        ),
    ]
