# Generated by Django 4.1.1 on 2022-11-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_alter_registration_face_to_face_fdp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBoxAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox', models.BooleanField(default=False)),
            ],
        ),
    ]
